#!/usr/bin/env bash
# A script to displays the contents of the file `/etc/passwd`.
# Your script should only display:
# . username
# . user id
# . Home directory path for the user

file_path='/etc/passwd'
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$file_path"
