#!/usr/bin/env bash
# A script to displays Best School 10 times and hi after the 9th using while loop and if statement

count=1

while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    ((count++))
done
