#!/usr/bin/env bash
# This script displays the content:
# The content of the current directory.
# In a list format.
# Where only the part of the name after the first dash is displayed.

for count in *
do
  echo "$count" | cut -d'-' -f2
done
